# Put this file (on our AWS LightSail server) in: /etc/nginx/sites-available/dmichaels.dev
# Check and restart nginx like this: sudo nginx -t ; sudo systemctl reload nginx
# Run the our Python scripts e.g.:
# - python3 ios_logicard_server.py --port 8001        > ios_logicard_server.log 2>&1 &
# - python3 ios_logicard_server_legacy.py --port 8000 > ios_logicard_server_legacy.log 2>&1 &
# Note that we registered SSL certificates like this:
# - sudo certbot certonly --standalone -d dmichaels.dev
# - sudo certbot certonly --standalone -d dmichaels.dev -d www.dmichaels.dev
# - sudo certbot certonly --standalone -d api.logicard.dmichaels.dev
# Note that the dmichaels.dev domain is registered at Squarespace.

server {
    listen 80;
    server_name dmichaels.dev;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name dmichaels.dev;

    ssl_certificate     /etc/letsencrypt/live/dmichaels.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dmichaels.dev/privkey.pem;

    location / {
        root /var/www/html;
        index index.html;
        try_files $uri $uri/ =404;
    }

    location /apis/logicard/legacy/ {
        proxy_pass http://127.0.0.1:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /apis/logicard/ {
        proxy_pass http://127.0.0.1:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 80;
    server_name api.logicard.dmichaels.dev;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.logicard.dmichaels.dev;

    ssl_certificate     /etc/letsencrypt/live/api.logicard.dmichaels.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.logicard.dmichaels.dev/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
