#!/bin/bash
HOST=http://127.0.0.1:8001
METHOD=GET
APIKEY=.0turangalila
URL="$HOST/$*"
echo $METHOD $URL
curl -s \
  -H "X-API-Key: $APIKEY" \
  -H "Content-Type: application/json" \
  -X $METHOD "$URL" \
   | python -m json.tool
