#!/bin/bash
HOST=http://127.0.0.1:8001
METHOD=POST
APIKEY=.0turangalila
URL="$HOST/$1"
if [ $# -ge 2 ] && [ -n "$2" ]; then
    DATA=(-d "$2")
else
    DATA=()
fi
echo $METHOD $URL
curl -s \
  -H "X-API-Key: $APIKEY" \
  -H "Content-Type: application/json" \
  -X $METHOD "$URL" \
  "${DATA[@]}" \
  | python -m json.tool
